<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/lesson12_chiziqli_algebra_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y = np.array([[5.,5.,5.], [4.,4.,4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [5]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [6]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [7]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [12]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
x


array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
y = np.array([[6.,23.], [-1,7],[8,9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [15]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [16]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [17]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [18]:
# Liner Algebra

from numpy.linalg import inv

In [19]:
T2 = np.random.randint(10 ,size=(2,2,2,2))

In [20]:
T2.shape

(2, 2, 2, 2)

In [21]:
T2.size

16

In [22]:
T2

array([[[[9, 9],
         [8, 9]],

        [[9, 6],
         [3, 2]]],


       [[[4, 5],
         [7, 5]],

        [[2, 7],
         [2, 8]]]])

In [25]:
v1 =np.array([1,2,3,4]) # massiv skalerga kopaytirilsa massivning har bir elementi skaler bilan kopaytiriladi

v1*4

array([ 4,  8, 12, 16])

In [29]:
v1 = np.array([1,2,3])
v2 = np.array([2,2,1])
np.dot(v1,v2)

9

In [30]:
A = np.random.randint(5 , size = (3,3))
A

array([[3, 3, 3],
       [0, 1, 4],
       [4, 0, 3]])

In [31]:
I3 = np.identity(3,dtype=int)
I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
I4 = np.identity(4,dtype=int)
I4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
A

array([[3, 3, 3],
       [0, 1, 4],
       [4, 0, 3]])