<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/lesson7_mantiqiy_oerator_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Massivga yonaltirilgan dasturlash.
Mantiqiy shart operatorini massiv operatori sifatida qo'llash.
Shart operatori sifatida **where** dan foydalanish



 Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular. **xarr** va **yarr** . Agarda shart **True**ni qanoatlantirsa **xarr** elementini qabul qilgan aksincha esa **yarr** elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar
xarr = np.array([1.1,1.2,1.3,1.4,1.5]) #xarr
yarr = np.array([2.1,2.2,2.3,2.4,2.5]) #yarr

In [3]:
# Shart
cond = np.array([True, False, True, True, False])

In [4]:
reult = np.where(cond,xarr,yarr) # cond==True : xarr elementi, cond==False : yarr elementi
reult

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.rand(4,4) # (4 , 4) ga olchamli massiv
arr

array([[0.09609405, 0.14409572, 0.62175475, 0.68352023],
       [0.25267616, 0.62836153, 0.07232716, 0.9726022 ],
       [0.68124415, 0.45155974, 0.17093721, 0.08864171],
       [0.57479175, 0.80055446, 0.79878448, 0.62976528]])

In [6]:
# where
result= np.where(arr<0, -2, 2) # arr ning manviy elementlarini -2 ga musbat 2 ga almawtirish
result

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [7]:
arr1 = np.random.randn(5,5) # massiv
arr1

array([[ 0.33548472,  0.12874172,  0.38284165, -2.17985077, -0.54471178],
       [ 0.01412571,  0.73168712, -0.46632726, -0.20594898,  0.07315628],
       [-0.0039371 , -0.45479045, -1.05828738, -0.58577143,  0.82035143],
       [-2.59679041, -0.34269671,  0.55919468,  0.34899993,  0.53910345],
       [ 0.37676354, -0.18890909, -0.20572779,  0.94867909, -0.90064399]])

In [8]:
results = np.where(arr1 <0, -1, 3)
results

array([[ 3,  3,  3, -1, -1],
       [ 3,  3, -1, -1,  3],
       [-1, -1, -1, -1,  3],
       [-1, -1,  3,  3,  3],
       [ 3, -1, -1,  3, -1]])

In [9]:
arr2 = np.random.randn(5,5,5)
arr2

array([[[ 6.59400735e-01, -7.24864931e-01,  5.19836595e-02,
         -1.59465615e-01,  3.52853425e-02],
        [ 8.27138266e-01,  7.09651884e-01, -6.26416224e-01,
          6.85705532e-01,  6.46130470e-02],
        [ 1.09242506e+00, -7.11278466e-01, -8.06948714e-02,
         -7.02887235e-01, -4.20103041e-01],
        [-5.55016172e-02,  1.37261736e+00, -1.07124857e+00,
          1.50339252e-01,  4.08718875e-01],
        [-1.05928080e+00,  5.19199730e-01, -6.05541402e-01,
          1.74955227e+00, -2.40507556e-03]],

       [[-3.01683289e-02, -7.36537889e-01,  1.77939447e+00,
          2.48305721e+00,  1.00590419e+00],
        [-1.93882130e+00,  5.89224149e-02,  8.62706941e-01,
          4.21219832e-01, -8.65842354e-01],
        [ 1.49323790e+00, -3.66571872e-01, -9.89204799e-01,
         -3.13497104e-01,  5.25185961e-03],
        [-1.20266953e+00, -1.56874464e+00,  1.34663748e+00,
         -6.82094837e-01, -1.80636776e+00],
        [ 1.02372684e+00, -1.82118022e+00,  1.75723968e+00,
  

In [10]:
result1 = np.where(arr2 <0, -5, 9)
result1

array([[[ 9, -5,  9, -5,  9],
        [ 9,  9, -5,  9,  9],
        [ 9, -5, -5, -5, -5],
        [-5,  9, -5,  9,  9],
        [-5,  9, -5,  9, -5]],

       [[-5, -5,  9,  9,  9],
        [-5,  9,  9,  9, -5],
        [ 9, -5, -5, -5,  9],
        [-5, -5,  9, -5, -5],
        [ 9, -5,  9, -5, -5]],

       [[ 9,  9, -5, -5,  9],
        [-5, -5, -5,  9,  9],
        [-5,  9,  9, -5, -5],
        [ 9, -5,  9,  9, -5],
        [-5,  9, -5, -5, -5]],

       [[-5, -5, -5, -5,  9],
        [ 9,  9, -5,  9, -5],
        [-5,  9, -5,  9, -5],
        [ 9, -5,  9,  9, -5],
        [-5,  9, -5, -5,  9]],

       [[ 9, -5,  9, -5,  9],
        [ 9, -5,  9,  9,  9],
        [ 9, -5,  9, -5, -5],
        [-5,  9,  9, -5,  9],
        [ 9,  9, -5,  9, -5]]])