<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/lesson11_fayillarBilan_ishlash_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data', arr)

In [5]:
np.load('data.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2 = np.load('data.npy')

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.arange(20)

In [15]:
np.savez('arrays', a =arr, b=arr1)

In [17]:
arrays =np.load('arrays.npz')

In [18]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
fayl = np.savez_compressed('array_comp', a = arr, b=arr1)