<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/lesson8_arifmetik_amallar_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(6).reshape(2,3) # 0-6 gacha bolgan elementlardan tashkil topgan array
arr2 = np.arange(6,12).reshape(2,3) # 6-11 gacha bolgan elementlardan tashkil topgan


In [3]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr*arr2 # array elementlarini arr2 ning mos elementlariga kopaytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
arr/arr2

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [8]:
arr+arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [9]:
arr-arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [10]:
# kvadiratga oshirish (square)
arr**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [11]:
#kvadirat ildiz (sqrt)
arr2*0.5

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])