<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/lesson4_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Boolean Indexlash

In [1]:
import numpy as np

In [2]:
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Mansur','Javohir','Alisher'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Mansur', 'Javohir',
       'Alisher'], dtype='<U8')

In [3]:
# data
data = np.random.randn(7,4)
data

array([[ 0.24228304,  2.30128662, -1.17655999, -0.18310711],
       [ 1.46105265,  0.82197193, -0.1709851 , -0.03835451],
       [ 0.30206235, -0.72092843, -1.94127293, -1.11370714],
       [ 0.78563692,  0.57227399,  1.30874024, -1.33486272],
       [-0.31153012,  3.31811973, -1.28405102,  1.15332078],
       [ 0.3417003 ,  2.38372316, -1.48442199, -0.93618057],
       [ 0.83892115, -1.38342366, -0.53232165, -0.00804731]])

In [4]:
names == 'Hasan'

array([ True, False, False, False, False, False, False])

In [5]:
data[names=='Hasan'] # hasanga tegishli barcha malumotlarni kesib olish

array([[ 0.24228304,  2.30128662, -1.17655999, -0.18310711]])

In [6]:
data[names=='Alisher'] # Alisherga tegishli malumotlarni ajratib olish

array([[ 0.83892115, -1.38342366, -0.53232165, -0.00804731]])

In [7]:
data[names =='Hasan',2:] # hasanga tegishli oxirgi 2 ta stundagi malumotlarni ajratib olish

array([[-1.17655999, -0.18310711]])

In [8]:
data[names =='Alisher', :2]

array([[ 0.83892115, -1.38342366]])

In [9]:
data[names!='Hasan'] # (!=) hasandan tashqari barcha insonlarni ajratib olish

array([[ 1.46105265,  0.82197193, -0.1709851 , -0.03835451],
       [ 0.30206235, -0.72092843, -1.94127293, -1.11370714],
       [ 0.78563692,  0.57227399,  1.30874024, -1.33486272],
       [-0.31153012,  3.31811973, -1.28405102,  1.15332078],
       [ 0.3417003 ,  2.38372316, -1.48442199, -0.93618057],
       [ 0.83892115, -1.38342366, -0.53232165, -0.00804731]])

In [10]:
data[~(names == 'Hasan')] # yuqoridagi cell bilan bir xil

array([[ 1.46105265,  0.82197193, -0.1709851 , -0.03835451],
       [ 0.30206235, -0.72092843, -1.94127293, -1.11370714],
       [ 0.78563692,  0.57227399,  1.30874024, -1.33486272],
       [-0.31153012,  3.31811973, -1.28405102,  1.15332078],
       [ 0.3417003 ,  2.38372316, -1.48442199, -0.93618057],
       [ 0.83892115, -1.38342366, -0.53232165, -0.00804731]])

In [17]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Mansur' 'Javohir' 'Alisher']
[[ 0.24228304  2.30128662 -1.17655999 -0.18310711]
 [ 1.46105265  0.82197193 -0.1709851  -0.03835451]
 [ 0.30206235 -0.72092843 -1.94127293 -1.11370714]
 [ 0.78563692  0.57227399  1.30874024 -1.33486272]
 [-0.31153012  3.31811973 -1.28405102  1.15332078]
 [ 0.3417003   2.38372316 -1.48442199 -0.93618057]
 [ 0.83892115 -1.38342366 -0.53232165 -0.00804731]]


In [19]:
mask = (names == 'Hasan') | (names == 'Husan') # ( | ) or yoki
mask

array([ True,  True, False, False, False, False, False])

In [20]:
data[mask] # hasan va husanga tegishli malumotlarni beradi

array([[ 0.24228304,  2.30128662, -1.17655999, -0.18310711],
       [ 1.46105265,  0.82197193, -0.1709851 , -0.03835451]])

In [23]:
data


array([[0.24228304, 2.30128662, 0.        , 0.        ],
       [1.46105265, 0.82197193, 0.        , 0.        ],
       [0.30206235, 0.        , 0.        , 0.        ],
       [0.78563692, 0.57227399, 1.30874024, 0.        ],
       [0.        , 3.31811973, 0.        , 1.15332078],
       [0.3417003 , 2.38372316, 0.        , 0.        ],
       [0.83892115, 0.        , 0.        , 0.        ]])

In [26]:
data[data<0]=0
data

array([[0.24228304, 2.30128662, 0.        , 0.        ],
       [1.46105265, 0.82197193, 0.        , 0.        ],
       [0.30206235, 0.        , 0.        , 0.        ],
       [0.78563692, 0.57227399, 1.30874024, 0.        ],
       [0.        , 3.31811973, 0.        , 1.15332078],
       [0.3417003 , 2.38372316, 0.        , 0.        ],
       [0.83892115, 0.        , 0.        , 0.        ]])