<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/DataScience/blob/main/tartiblash_sorting_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Tartiblash (**sorting**)

In [3]:
# data
arr = np.random.randn(4) # 4 ta taxminiy elementlardan tawkil topgan massi
arr

array([-0.54035116,  1.40908976,  0.37564489, -0.88077029])

**sort** funksiyasi

In [4]:
sorted_arr = np.sort(arr) # arr massivning tartiblangan versiyasi

In [5]:
sorted_arr

array([-0.88077029, -0.54035116,  0.37564489,  1.40908976])

In [6]:
# 2 usul
arr.sort() # arr ning tartiblangan korinishi
arr

array([-0.88077029, -0.54035116,  0.37564489,  1.40908976])

In [8]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # bu teskari tarkibdagi arr
rev_arr

array([ 1.40908976,  0.37564489, -0.54035116, -0.88077029])

In [11]:
# 2 D array (massiv)
arr2d = np.random.randn(2,4 ) # (2, 4 ) random massiv
arr2d

array([[ 0.62113226,  0.99162937, -0.26906581, -1.56218858],
       [-0.83568802, -0.85965447, -0.47987434,  0.28723305]])

In [12]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis =0) # arr2d har bir qator boyicha tartiublangan massiv
row_srt

array([[-0.83568802, -0.85965447, -0.47987434, -1.56218858],
       [ 0.62113226,  0.99162937, -0.26906581,  0.28723305]])

In [16]:
col1 = np.sort(arr2d, axis = 1) # arr2d sutun boyicha tartiblangan massiv
col1

array([[-1.56218858, -0.26906581,  0.62113226,  0.99162937],
       [-0.85965447, -0.83568802, -0.47987434,  0.28723305]])

In [18]:
col = -np.sort(-arr2d, axis=1)
col

array([[ 0.99162937,  0.62113226, -0.26906581, -1.56218858],
       [ 0.28723305, -0.47987434, -0.83568802, -0.85965447]])

In [19]:
son = -np.sort(-arr2d, axis = 0)
arr2d

array([[ 0.62113226,  0.99162937, -0.26906581, -1.56218858],
       [-0.83568802, -0.85965447, -0.47987434,  0.28723305]])